# Generated by Django 3.1.7 on 2021-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Yasin', 'Yasin'), ('Narges', 'Narges'), ('Ardalan', 'Ardalan'), ('Atid', 'Atid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
