# Generated by Django 3.1.7 on 2021-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210901_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Narges', 'Narges'), ('Yasin', 'Yasin'), ('Atid', 'Atid'), ('Ardalan', 'Ardalan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('5', '5'), ('1', '1'), ('4', '4')], max_length=1),
        ),
    ]
