# Generated by Django 3.1.7 on 2021-09-02 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210902_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodargus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 11, 23, 54, 47837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Narges', 'Narges'), ('Atid', 'Atid'), ('Yasin', 'Yasin'), ('Ardalan', 'Ardalan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('2', '2'), ('5', '5')], max_length=1),
        ),
    ]
