# Generated by Django 3.1.7 on 2021-09-05 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210902_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Ardalan', 'Ardalan'), ('Yasin', 'Yasin'), ('Narges', 'Narges'), ('Atid', 'Atid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
