# Generated by Django 3.1.7 on 2021-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210909_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='check',
            field=models.BooleanField(default=False, verbose_name='آیا اجازه دارید؟'),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1')], max_length=1),
        ),
    ]
