# Generated by Django 3.1.7 on 2021-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20210909_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Atid', 'Atid'), ('Ardalan', 'Ardalan'), ('Yasin', 'Yasin'), ('Narges', 'Narges')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='group',
            field=models.ManyToManyField(related_name='articles', to='food.category'),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('5', '5'), ('4', '4'), ('2', '2')], max_length=1),
        ),
    ]
