# Generated by Django 3.1.7 on 2021-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210909_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Yasin', 'Yasin'), ('Atid', 'Atid'), ('Ardalan', 'Ardalan'), ('Narges', 'Narges')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=1),
        ),
    ]
