# Generated by Django 3.1.7 on 2021-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210909_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Atid', 'Atid'), ('Ardalan', 'Ardalan'), ('Narges', 'Narges'), ('Yasin', 'Yasin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('4', '4'), ('3', '3'), ('1', '1')], max_length=1),
        ),
    ]
