# Generated by Django 3.1.7 on 2021-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210909_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='theslg',
            field=models.SlugField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Atid', 'Atid'), ('Narges', 'Narges'), ('Yasin', 'Yasin'), ('Ardalan', 'Ardalan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('4', '4'), ('3', '3'), ('1', '1')], max_length=1),
        ),
    ]
