# Generated by Django 3.1.7 on 2021-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210909_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Narges', 'Narges'), ('Ardalan', 'Ardalan'), ('Atid', 'Atid'), ('Yasin', 'Yasin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('1', '1'), ('5', '5'), ('3', '3')], max_length=1),
        ),
    ]
