# Generated by Django 3.1.7 on 2021-09-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20210910_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='food.category'),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='auth',
            field=models.CharField(choices=[('Narges', 'Narges'), ('Yasin', 'Yasin'), ('Ardalan', 'Ardalan'), ('Atid', 'Atid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('5', '5'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
