# Generated by Django 3.2.7 on 2021-09-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20210912_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__id',), 'verbose_name': 'گروه', 'verbose_name_plural': 'گروه\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodargus',
            name='rate',
            field=models.CharField(choices=[('Best', (('1', '1'), ('2', '2'), ('3', '3'))), ('Nice', (('4', '4'), ('5', '5')))], max_length=1),
        ),
    ]
